spring:
  application:
    name: greenting-service
  cloud:
    config:
      enabled: false
greenting-service:
  greenting: "Hola"
  default-value: "Mundo"
management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
